apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medaudit

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - storage-pvc.yaml
  - postgres-statefulset.yaml
  - redis-statefulset.yaml
  - backend-deployment.yaml
  - backend-hpa.yaml
  - celery-deployment.yaml
  - celery-hpa.yaml
  - ingress.yaml

commonLabels:
  app: medaudit
  version: v1.0.0



